sudo: false
language: node_js
notifications:
  email: false
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
script:
  # Unit test & code style
  - npm test

  # Integration test
  - npm run build
  - cd examples
  - yarn install
  - yarn bootstrap
  - yarn test
after_script:
  - cd ..
  - greenkeeper-lockfile-upload
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
