sudo: false
language: node_js
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn lint
  - yarn test --coverage

  # Integration test
  - yarn build
  - cd examples
  - yarn
  - yarn bootstrap
  - yarn test
  - cd ..
after_success:
  - yarn release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
