sudo: false
language: node_js
notifications:
  email: false
script:
  # Unit test & code style
  - npm test

  # Integration test
  - npm run build
  - cd examples
  - yarn install
  - yarn bootstrap
  - yarn test
  - cd ..
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
